name: TnTSlap
main: com.Nips.TnTSlap.TnTSlap
version: 1.00.0
author: d3sty
description: Gold old slap game, with a twist.
commands:
  tntslap:
    aliases: ts
    description: stuff.
    usage: /<command>
  arena:
    aliases: a
    description: stuff.
    usage: /<command>
permissions:
  tntslap.items.butter:
    description: Use butter instead of slap o fish
  tntslap.set.*:
    description: Allow all set perms
    children:
      tntslap.set.nextmap: true
      tntslap.set.gamestate: true
  tntslap.set.nextmap:
    description: Allow user to set next map
  tntslap.set.gamestate:
    description: Aloow user to stop or start game