name: TnTSlap
main: com.Nips.TnTSlap.TnTSlap
version: 1.00.0
author: d3sty & Kunta
description: Gold old slap game, with a twist.
commands:
  tntslap:
    aliases: ts
    description: stuff.
    usage: /<command>
  setarena:
    aliases: sa
    description: stuff.
    usage: /<command>
#fdjksafda